### ISSUE TITLE
File size and virus detection 

### ISSUE THREAD

**Issue by Kiho-Kwon** [PathOfBuildingCommunity/PathOfBuilding-Launcher#2]
I built this launcher, but it has a file size of about 300kb or more. 
It's different from what's distributed (I built it in VS2019 and it's in release mode) 
and some virus detection programs (like Kaspersky) recognize it as a Trojan. 

Can you see why?

**Comment by dclamage** [comment]
This launcher has not been released yet. The launcher used by the current release is still the original one created by openarl. This one is larger because it statically links the CRT to avoid installation dependencies.

As for virus detection, this launcher is very simple. It's probably a heuristic detection, but I don't really know how to avoid that.

**Comment by Kiho-Kwon** [comment]
Thank you for your grateful comments.
